
title: Francesco Stasi
email: f.stasi@me.com
author: fstasi
theme: plainwhite
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
show_excerpts: true

plainwhite:
  name: Francesco Stasi
  tagline: I write code
  date_format: "%b %-d, %Y"
  portfolio_image:  "assets/portfolio.png"
  html_lang: "en" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp
  condensed_mobile:
    - page
    - post
  social_links:
    twitter: _fstasi
    github:  fstasi
    linkedIn: in/fstasi